// Code generated by go generate; DO NOT EDIT.

package dsl

import "github.com/trustmaster/goflow/dsl/types"

func generatedIndex(v int) *int { return &v }

var generatedTopLevelDefinition = types.Definition{
	Processes: map[string]types.ProcessDef{
		"Lexer": {
			Name:      "Lexer",
			Component: "dsl/Lexer",
		},
		"Parser": {
			Name:      "Parser",
			Component: "dsl/Parser",
		},
		"SegmentStatements": {
			Name:      "SegmentStatements",
			Component: "dsl/SegmentStatements",
		},
		"StripTrivia": {
			Name:      "StripTrivia",
			Component: "dsl/StripTrivia",
		},
	},
	Connections: []types.ConnectionDef{
		{
			Src: types.Endpoint{
				Process: "Lexer",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "StripTrivia",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "StripTrivia",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "SegmentStatements",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "SegmentStatements",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Parser",
				Port:    "In",
			},
		},
	},
	IIPs: []types.IIPDef{},
	Exports: []types.ExportDef{
		{
			Kind:   types.ExportInPort,
			Public: "In",
			Proc:   "Lexer",
			Port:   "In",
		},
		{
			Kind:   types.ExportOutPort,
			Public: "Out",
			Proc:   "Parser",
			Port:   "Out",
		},
	},
}
