# Dockerfile to help developers test their current build
# To use:
#  docker build -t my_tag -f Dockerfile.dev .
#  docker run -v `pwd`/..:/go/src/github.com/Synthace -it my_tag
#   <run commands in container>
#   exit
# <edit files in `pwd`/..>
# docker run -v `pwd`/..:/go/src/github.com/Synthace -it my_tag
#   <...>
FROM golang:1.4

#RUN apt-get update && apt-get install -y libglpk-dev libsqlite3-dev && rm -rf /var/lib/apt/lists/*

VOLUME /go/src/github.com/Synthace
WORKDIR /go/src/github.com/Synthace/goflow
