// Code generated by go generate; DO NOT EDIT.

package lex

import "github.com/trustmaster/goflow/dsl/types"

func generatedIndex(v int) *int { return &v }

var generatedLexerDefinition = types.Definition{
	Processes: map[string]types.ProcessDef{
		"Advance": {
			Name:      "Advance",
			Component: "dsl/Advance",
		},
		"Dispatch": {
			Name:      "Dispatch",
			Component: "dsl/Dispatch",
		},
		"ScanComment": {
			Name:      "ScanComment",
			Component: "dsl/ScanCommentToken",
		},
		"ScanIdent": {
			Name:      "ScanIdent",
			Component: "dsl/ScanIdentToken",
		},
		"ScanNumber": {
			Name:      "ScanNumber",
			Component: "dsl/ScanNumberToken",
		},
		"ScanOperator": {
			Name:      "ScanOperator",
			Component: "dsl/ScanOperatorToken",
		},
		"ScanQuoted": {
			Name:      "ScanQuoted",
			Component: "dsl/ScanQuotedToken",
		},
		"ScanWhitespace": {
			Name:      "ScanWhitespace",
			Component: "dsl/ScanWhitespaceToken",
		},
		"StartCursor": {
			Name:      "StartCursor",
			Component: "dsl/StartCursor",
		},
	},
	Connections: []types.ConnectionDef{
		{
			Src: types.Endpoint{
				Process: "StartCursor",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Dispatch",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Advance",
				Port:    "Next",
			},
			Tgt: types.Endpoint{
				Process: "Dispatch",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Dispatch",
				Port:    "Whitespace",
			},
			Tgt: types.Endpoint{
				Process: "ScanWhitespace",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Dispatch",
				Port:    "Comment",
			},
			Tgt: types.Endpoint{
				Process: "ScanComment",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Dispatch",
				Port:    "Quoted",
			},
			Tgt: types.Endpoint{
				Process: "ScanQuoted",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Dispatch",
				Port:    "Ident",
			},
			Tgt: types.Endpoint{
				Process: "ScanIdent",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Dispatch",
				Port:    "Number",
			},
			Tgt: types.Endpoint{
				Process: "ScanNumber",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Dispatch",
				Port:    "Operator",
			},
			Tgt: types.Endpoint{
				Process: "ScanOperator",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "Dispatch",
				Port:    "Eof",
			},
			Tgt: types.Endpoint{
				Process: "Advance",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ScanWhitespace",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Advance",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ScanComment",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Advance",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ScanQuoted",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Advance",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ScanIdent",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Advance",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ScanNumber",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Advance",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ScanOperator",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "Advance",
				Port:    "In",
			},
		},
	},
	IIPs: []types.IIPDef{},
	Exports: []types.ExportDef{
		{
			Kind:   types.ExportInPort,
			Public: "In",
			Proc:   "StartCursor",
			Port:   "File",
		},
		{
			Kind:   types.ExportOutPort,
			Public: "Out",
			Proc:   "Advance",
			Port:   "Out",
		},
	},
}
