// Code generated by go generate; DO NOT EDIT.

package parse

import "github.com/trustmaster/goflow/dsl/types"

func generatedIndex(v int) *int { return &v }

var generatedParserDefinition = types.Definition{
	Processes: map[string]types.ProcessDef{
		"CollectDefinition": {
			Name:      "CollectDefinition",
			Component: "dsl/CollectDefinition",
		},
		"ParseConnection": {
			Name:      "ParseConnection",
			Component: "dsl/ParseConnection",
		},
		"ParseExport": {
			Name:      "ParseExport",
			Component: "dsl/ParseExport",
		},
		"ParseIIP": {
			Name:      "ParseIIP",
			Component: "dsl/ParseIIP",
		},
		"RouteStatements": {
			Name:      "RouteStatements",
			Component: "dsl/RouteStatements",
		},
	},
	Connections: []types.ConnectionDef{
		{
			Src: types.Endpoint{
				Process: "RouteStatements",
				Port:    "Export",
			},
			Tgt: types.Endpoint{
				Process: "ParseExport",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "RouteStatements",
				Port:    "Iip",
			},
			Tgt: types.Endpoint{
				Process: "ParseIIP",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "RouteStatements",
				Port:    "Connection",
			},
			Tgt: types.Endpoint{
				Process: "ParseConnection",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ParseExport",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "CollectDefinition",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ParseIIP",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "CollectDefinition",
				Port:    "In",
			},
		},
		{
			Src: types.Endpoint{
				Process: "ParseConnection",
				Port:    "Out",
			},
			Tgt: types.Endpoint{
				Process: "CollectDefinition",
				Port:    "In",
			},
		},
	},
	IIPs: []types.IIPDef{},
	Exports: []types.ExportDef{
		{
			Kind:   types.ExportInPort,
			Public: "In",
			Proc:   "RouteStatements",
			Port:   "In",
		},
		{
			Kind:   types.ExportOutPort,
			Public: "Out",
			Proc:   "CollectDefinition",
			Port:   "Out",
		},
	},
}
