package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"

	"github.com/trustmaster/goflow/dsl"
	"github.com/trustmaster/goflow/dsl/types"
)

type target struct {
	inputPath    string
	outputPath   string
	packageName  string
	variableName string
}

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	targets := []target{
		{
			inputPath:    "dsl.fbp",
			outputPath:   "internal_defs_gen.go",
			packageName:  "dsl",
			variableName: "generatedTopLevelDefinition",
		},
		{
			inputPath:    "lex/lexer.fbp",
			outputPath:   "lex/internal_defs_gen.go",
			packageName:  "lex",
			variableName: "generatedLexerDefinition",
		},
		{
			inputPath:    "parse/parser.fbp",
			outputPath:   "parse/internal_defs_gen.go",
			packageName:  "parse",
			variableName: "generatedParserDefinition",
		},
	}

	for i := range targets {
		def, err := dsl.LoadDefinitionFile(targets[i].inputPath)
		if err != nil {
			return fmt.Errorf("parse %s: %w", targets[i].inputPath, err)
		}

		if err := writeDefinitionFile(targets[i], def); err != nil {
			return err
		}
	}

	return nil
}

func writeDefinitionFile(t target, def *types.Definition) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buf.WriteString("package " + t.packageName + "\n\n")
	buf.WriteString("import \"github.com/trustmaster/goflow/dsl/types\"\n\n")
	buf.WriteString("func generatedIndex(v int) *int { return &v }\n\n")
	buf.WriteString("var " + t.variableName + " = ")

	if err := emitDefinition(&buf, *def, ""); err != nil {
		return fmt.Errorf("emit %s: %w", t.outputPath, err)
	}

	buf.WriteByte('\n')

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format %s: %w", t.outputPath, err)
	}

	if err := os.WriteFile(t.outputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", t.outputPath, err)
	}

	return nil
}

func emitDefinition(buf *bytes.Buffer, def types.Definition, indent string) error {
	next := indent + "\t"

	buf.WriteString("types.Definition{\n")

	emitProcesses(buf, def.Processes, next)

	buf.WriteString(next + "Connections: []types.ConnectionDef{\n")
	for i := range def.Connections {
		buf.WriteString(next + "\t{\n")
		buf.WriteString(next + "\t\tSrc: ")
		emitEndpoint(buf, def.Connections[i].Src, next+"\t\t")
		buf.WriteString(",\n")
		buf.WriteString(next + "\t\tTgt: ")
		emitEndpoint(buf, def.Connections[i].Tgt, next+"\t\t")
		buf.WriteString(",\n")
		buf.WriteString(next + "\t},\n")
	}
	buf.WriteString(next + "},\n")

	buf.WriteString(next + "IIPs: []types.IIPDef{\n")
	for i := range def.IIPs {
		lit, err := literalFor(def.IIPs[i].Data)
		if err != nil {
			return err
		}

		buf.WriteString(next + "\t{\n")
		buf.WriteString(next + "\t\tData: " + lit + ",\n")
		buf.WriteString(next + "\t\tTgt: ")
		emitEndpoint(buf, def.IIPs[i].Tgt, next+"\t\t")
		buf.WriteString(",\n")
		buf.WriteString(next + "\t},\n")
	}
	buf.WriteString(next + "},\n")

	buf.WriteString(next + "Exports: []types.ExportDef{\n")
	for i := range def.Exports {
		exp := def.Exports[i]
		buf.WriteString(next + "\t{\n")
		buf.WriteString(next + "\t\tKind: " + exportKindLiteral(exp.Kind) + ",\n")
		buf.WriteString(next + "\t\tPublic: " + strconv.Quote(exp.Public) + ",\n")
		buf.WriteString(next + "\t\tProc: " + strconv.Quote(exp.Proc) + ",\n")
		buf.WriteString(next + "\t\tPort: " + strconv.Quote(exp.Port) + ",\n")
		buf.WriteString(next + "\t},\n")
	}
	buf.WriteString(next + "},\n")

	buf.WriteString(indent + "}")

	return nil
}

func emitProcesses(buf *bytes.Buffer, processes map[string]types.ProcessDef, indent string) {
	names := make([]string, 0, len(processes))
	for name := range processes {
		names = append(names, name)
	}
	sort.Strings(names)

	buf.WriteString(indent + "Processes: map[string]types.ProcessDef{\n")
	for i := range names {
		proc := processes[names[i]]
		buf.WriteString(indent + "\t" + strconv.Quote(names[i]) + ": {\n")
		buf.WriteString(indent + "\t\tName: " + strconv.Quote(proc.Name) + ",\n")
		buf.WriteString(indent + "\t\tComponent: " + strconv.Quote(proc.Component) + ",\n")
		buf.WriteString(indent + "\t},\n")
	}
	buf.WriteString(indent + "},\n")
}

func emitEndpoint(buf *bytes.Buffer, ep types.Endpoint, indent string) {
	buf.WriteString("types.Endpoint{\n")
	buf.WriteString(indent + "\tProcess: " + strconv.Quote(ep.Process) + ",\n")
	buf.WriteString(indent + "\tPort: " + strconv.Quote(ep.Port) + ",\n")
	if ep.Index != nil {
		buf.WriteString(indent + "\tIndex: generatedIndex(" + strconv.Itoa(*ep.Index) + "),\n")
	}
	buf.WriteString(indent + "}")
}

func exportKindLiteral(kind types.ExportKind) string {
	switch kind {
	case types.ExportInPort:
		return "types.ExportInPort"
	case types.ExportOutPort:
		return "types.ExportOutPort"
	default:
		return strconv.Quote(string(kind))
	}
}

func literalFor(v any) (string, error) {
	switch value := v.(type) {
	case nil:
		return "nil", nil
	case string:
		return strconv.Quote(value), nil
	case int:
		return strconv.Itoa(value), nil
	case int8, int16, int32, int64:
		return fmt.Sprintf("%d", value), nil
	case uint, uint8, uint16, uint32, uint64:
		return fmt.Sprintf("%d", value), nil
	case float32:
		return strconv.FormatFloat(float64(value), 'g', -1, 32), nil
	case float64:
		return strconv.FormatFloat(value, 'g', -1, 64), nil
	case bool:
		return strconv.FormatBool(value), nil
	default:
		return "", fmt.Errorf("unsupported IIP data type %T", v)
	}
}
